name: Build Wheels
on:
  push:
    branches: [main]
  create:

jobs:
  build_wheels:
    strategy:
      matrix:
        os: [ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    name: Build wheels on ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64

      - name: Set up Python 3.10.4
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.4
          cache: "pip"

      - name: Prepare
        shell: bash
        run: |
          pwd
          pip install -r requirements.txt
          wget -nv -nc https://files.pythonhosted.org/packages/64/4a/b008d1f8a7b9f5206ecf70a53f84e654707e7616a771d84c05151a4713e9/numpy-1.22.3.zip
          tar -xvf *.tar.gz > /dev/null
          mv numpy*/* .
          pip install -U pip wheel setuptools cmake
      - name: Build
        uses: pypa/cibuildwheel@v2.4.0
        env:
          CIBW_PLATFORM: linux
          CIBW_BUILD: cp310-*_aarch64
          CIBW_ARCHS_LINUX: aarch64
          CIBW_SKIP: pp*
          CIBW_BEFORE_ALL:  "pwd"

      - name: Upload Wheels
        uses: actions/upload-artifact@v1
        with:
          name: Wheels
          path: wheelhouse
