name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        shell: bash
        run: |
          python -m pip install cibuildwheel==2.4.0
          wget -nv -nc https://files.pythonhosted.org/packages/b4/a2/4faa34bf0cdbefd5c706625f1234987795f368eb4e97bde9d6f46860843e/scipy-1.8.0.tar.gz
          tar -xvf scipy-1.8.0.tar.gz > /dev/null
          mv scipy-1.8.0/* .
          rm -rf scipy-1.8.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse --archs aarch64
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
