name: Build Wheels

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        shell: bash
        run: |
          python -m pip install cibuildwheel==2.4.0
          wget -nv -nc https://files.pythonhosted.org/packages/e5/a4/47e425fed0a38bfb401f38946cf38361ae0ccc13b5250f34aced911b2701/fast-histogram-0.10.tar.gz
          tar -xvf fast-histogram-0.10 > /dev/null
          mv fast-histogram-0.10/* .

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse --archs aarch64
        # to supply options, put them in 'env', like:
        # env:
        #   CIBW_SOME_OPTION: value

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
